// Shared editable instructions; character sources and output language are appended separately.
export const DEFAULT_DESCRIPTION_PROMPT = "Build a complete character profile for injection into a roleplay prompt.\n\nReturn a compact dossier, not a literary paragraph: detailed enough to preserve appearance, background, voice, role, and internal logic in future scenes.\nUse the chat history, user persona, relationship dynamics, character card, creator notes, speech examples, and relevant world info / lorebook.\n\n[OUTPUT FORMAT]\nReturn only the finished profile in the requested output language, without markdown, explanations, or an introduction.\nWrite exactly 10 lines with the following fields. Translate the field labels into the requested output language:\nName: ...\nAge / life stage: ...\nRole and position: ...\nAppearance: ...\nClothing and distinctive details: ...\nPersonality and inner foundation: ...\nSpeech and behavior: ...\nBackground and personal context: ...\nAttitude toward the user: ...\nScene guide: ...\n\n[RULES]\n1. Complete the profile. Do not use placeholders such as \"not specified\", \"insufficient data\", \"maybe\", \"possibly\", or \"unclear\".\n2. Fill gaps carefully using established facts, scene tone, world info, the card, and observed behavior.\n3. Invent details only where they do not contradict explicit canon. Facts from the card, creator notes, world info, and chat take priority over inference.\n4. If several interpretations are possible, choose one plausible, consistent version instead of listing alternatives.\n5. Make appearance concrete: build, face, hair, eyes, voice, habits, scars, scent, or movement where appropriate.\n6. Give the background story hooks: origins, social position, connections, secrets, trauma, goals, fears, or obligations.\n7. Explain how to portray the character in the scene guide: reactions to emphasize, behavior to avoid, and sensitive topics.\n8. Preserve and expand useful facts from the current description.\n9. Every line must be substantial and ready for prompt injection, with no empty questionnaire fields.\n10. Keep the profile compact and dense, usually 1400-2800 characters.";
export const DESCRIPTION_PROMPT_LIMIT = 8000;
export function normalizeDescriptionPrompt(value) {
    return typeof value === "string" ? value.replace(/\r\n?/g, '\n').slice(0, DESCRIPTION_PROMPT_LIMIT).trim() : "";
}
export function resolveDescriptionPrompt(value) {
    return normalizeDescriptionPrompt(value) || DEFAULT_DESCRIPTION_PROMPT;
}
