/* global jQuery, SillyTavern */
import { extension_settings } from '../../../extensions.js';
import { MODULE_NAME, DEFAULT_SETTINGS, normalizeVnReplyLength } from './modules/constants.js';
import { 
    injectCombinedSocialPrompt, 
    recalculateAllStats, 
    setRenderHudCallback,
    getCombinedSocial,
    getCurrentPersonaScopeKey
} from './modules/social.js';
import { 
    ensureHudContainer, 
    updateHudVisibility, 
    renderSocialHud,
    openSocialHud,
    closeSocialHud
} from './modules/hud.js';
import { setupExtensionSettings, wipeGlobalLog, wipeAllSocialData, injectDebugData } from './modules/settings.js';
import { injectVNActionsUI } from './modules/actions.js';
import { restoreVNOptions, bbVnGenerateOptionsFlow, clearVNOptions } from './modules/generator.js';
import { setSocialParseDebug } from './modules/state.js';

// Глобальный экспорт для консоли и внешних вызовов
window['recalculateAllStats'] = recalculateAllStats;
window['getCombinedSocial'] = getCombinedSocial;
window['injectCombinedSocialPrompt'] = injectCombinedSocialPrompt;
window['bbVnGenerateOptionsFlow'] = bbVnGenerateOptionsFlow;
window['restoreVNOptions'] = restoreVNOptions;
window['clearVNOptions'] = clearVNOptions;
window['injectVNActionsUI'] = injectVNActionsUI;
window['setupExtensionSettings'] = setupExtensionSettings;
window['renderSocialHud'] = renderSocialHud;
window['openSocialHud'] = openSocialHud;
window['closeSocialHud'] = closeSocialHud;
window['wipeGlobalLog'] = wipeGlobalLog;
window['wipeAllSocialData'] = wipeAllSocialData;
window['updateHudVisibility'] = updateHudVisibility;
window['ensureHudContainer'] = ensureHudContainer;
window['injectDebugData'] = injectDebugData;

const PERSONA_SCOPE_POLL_MS = 350;
const AUTO_GEN_DELAY_MS = 900;
let personaScopeMonitorId = null;
let lastObservedPersonaScopeKey = '';
let autoGenTimerId = null;
let lastAutoGeneratedMessageKey = '';

// Инициализация настроек по умолчанию
extension_settings[MODULE_NAME] = {
    ...DEFAULT_SETTINGS,
    ...(extension_settings[MODULE_NAME] || {}),
};
extension_settings[MODULE_NAME].vnReplyLength = normalizeVnReplyLength(extension_settings[MODULE_NAME].vnReplyLength);

// Привязываем коллбэк отрисовки HUD к логике пересчета статов
setRenderHudCallback(renderSocialHud);

function replaceMacroDeep(target, promptText) {
    const macro = '{{bb_vn}}';
    const countOccurrences = (value) => {
        if (typeof value !== 'string' || !value.includes(macro)) return 0;
        return value.split(macro).length - 1;
    };

    const walk = (value) => {
        if (typeof value === 'string') {
            const replacements = countOccurrences(value);
            return {
                value: replacements > 0 ? value.replace(/\{\{bb_vn\}\}/g, promptText) : value,
                replacements,
            };
        }

        if (Array.isArray(value)) {
            let total = 0;
            for (let i = 0; i < value.length; i++) {
                const result = walk(value[i]);
                value[i] = result.value;
                total += result.replacements;
            }
            return { value, replacements: total };
        }

        if (value && typeof value === 'object') {
            let total = 0;
            for (const key of Object.keys(value)) {
                const result = walk(value[key]);
                value[key] = result.value;
                total += result.replacements;
            }
            return { value, replacements: total };
        }

        return { value, replacements: 0 };
    };

    return walk(target).replacements;
}

jQuery(async () => {
    try {
        const { eventSource, event_types } = SillyTavern.getContext();
        const clearScheduledAutoGen = () => {
            if (!autoGenTimerId) return;
            window.clearTimeout(autoGenTimerId);
            autoGenTimerId = null;
        };

        const getLatestAssistantMessageMeta = () => {
            const context = SillyTavern.getContext?.();
            const chat = Array.isArray(context?.chat) ? context.chat : [];
            const lastMessage = chat.length > 0 ? chat[chat.length - 1] : null;
            if (!lastMessage || lastMessage.is_user) return null;

            const messageText = String(lastMessage.mes || lastMessage.message || '').trim();
            const swipeId = String(lastMessage.swipe_id ?? '');
            const generationId = String(lastMessage.extra?.gen_id || lastMessage.extra?.generation_id || '');
            const messageName = String(lastMessage.name || lastMessage.original_name || '').trim();
            const messageIndex = chat.length - 1;

            return {
                key: [messageIndex, swipeId, generationId, messageName, messageText].join('|'),
                text: messageText,
            };
        };

        const getAutoGenEligibility = () => {
            if (!extension_settings[MODULE_NAME].autoGen) return { allowed: false, key: '' };

            const assistantMessage = getLatestAssistantMessageMeta();
            if (!assistantMessage?.key || !assistantMessage.text) return { allowed: false, key: '' };

            const textarea = document.querySelector('#send_textarea');
            if (textarea instanceof HTMLTextAreaElement && textarea.value.trim().length > 0) {
                return { allowed: false, key: assistantMessage.key };
            }

            const container = document.getElementById('bb-vn-options-container');
            if (container?.querySelector('.bb-vn-option[data-intent]')) {
                return { allowed: false, key: assistantMessage.key };
            }

            const generateButton = jQuery('#bb-vn-btn-generate');
            if (!generateButton.is(':visible') || generateButton.hasClass('loading')) {
                return { allowed: false, key: assistantMessage.key };
            }

            return { allowed: true, key: assistantMessage.key };
        };

        const scheduleAutoGenForLatestReply = () => {
            clearScheduledAutoGen();

            const eligibility = getAutoGenEligibility();
            if (!eligibility.allowed || !eligibility.key || eligibility.key === lastAutoGeneratedMessageKey) return;

            autoGenTimerId = window.setTimeout(() => {
                autoGenTimerId = null;
                const currentEligibility = getAutoGenEligibility();
                if (!currentEligibility.allowed || currentEligibility.key !== eligibility.key) return;
                if (currentEligibility.key === lastAutoGeneratedMessageKey) return;

                lastAutoGeneratedMessageKey = currentEligibility.key;
                void bbVnGenerateOptionsFlow();
            }, AUTO_GEN_DELAY_MS);
        };

        const syncPersonaScopeIfChanged = (force = false) => {
            if (typeof document !== 'undefined' && document.hidden) return;
            const currentScopeKey = getCurrentPersonaScopeKey();
            if (!force && currentScopeKey === lastObservedPersonaScopeKey) return;
            lastObservedPersonaScopeKey = currentScopeKey;
            restoreVNOptions(false);
            injectCombinedSocialPrompt();
            recalculateAllStats();
            updateHudVisibility();
        };

        const registerHudVisibilityRecoveryEvents = () => {
            const recoveryEventCandidates = [
                'CHAT_CREATED',
                'CHAT_LOADED',
                'CHARACTER_CHANGED',
                'GROUP_UPDATED',
                'GROUP_CHAT_CREATED',
                'GROUP_CHAT_DELETED',
                'IMPERSONATE_READY',
                'SETTINGS_LOADED_AFTER',
            ];

            recoveryEventCandidates.forEach((eventKey) => {
                const eventName = event_types[eventKey];
                if (!eventName) return;
                eventSource.on(eventName, () => {
                    injectCombinedSocialPrompt();
                    recalculateAllStats();
                    updateHudVisibility();
                });
            });
        };
        
        setupExtensionSettings();

        const context = SillyTavern.getContext();
        if (context.registerMacro) {
            context.registerMacro('bb_vn', () => {
                return extension_settings[MODULE_NAME].useMacro ? getCombinedSocial() : '';
            });
        }

        injectCombinedSocialPrompt();
        ensureHudContainer();
        injectVNActionsUI();
        updateHudVisibility();
        lastObservedPersonaScopeKey = getCurrentPersonaScopeKey();

        if (!personaScopeMonitorId) {
            personaScopeMonitorId = window.setInterval(() => {
                syncPersonaScopeIfChanged(false);
            }, PERSONA_SCOPE_POLL_MS);
        }

        eventSource.on(event_types.APP_READY, () => {
            clearScheduledAutoGen();
            lastAutoGeneratedMessageKey = '';
            setupExtensionSettings();
            injectCombinedSocialPrompt();
            ensureHudContainer();
            injectVNActionsUI();
            recalculateAllStats(); 
            updateHudVisibility();
            syncPersonaScopeIfChanged(true);
        });
        
        eventSource.on(event_types.CHAT_CHANGED, () => {
            clearScheduledAutoGen();
            lastAutoGeneratedMessageKey = '';
            restoreVNOptions(false);
            injectCombinedSocialPrompt();
            injectVNActionsUI();
            recalculateAllStats(); 
            updateHudVisibility();
            syncPersonaScopeIfChanged(true);
        });

        registerHudVisibilityRecoveryEvents();

        eventSource.on(event_types.MESSAGE_RECEIVED, () => {
            restoreVNOptions(false);
            recalculateAllStats(true);
            scheduleAutoGenForLatestReply();
        });
        eventSource.on(event_types.MESSAGE_DELETED, () => {
            clearScheduledAutoGen();
            restoreVNOptions(false);
            recalculateAllStats();
        });
        eventSource.on(event_types.MESSAGE_SWIPED, () => {
            clearScheduledAutoGen();
            restoreVNOptions(false);
            recalculateAllStats();
        });
        eventSource.on(event_types.MESSAGE_UPDATED, () => { recalculateAllStats(); });
        eventSource.on(event_types.GENERATION_STOPPED, () => {
            clearScheduledAutoGen();
            recalculateAllStats(true);
        });
        
        if (event_types.CHARACTER_MESSAGE_RENDERED) {
            eventSource.on(event_types.CHARACTER_MESSAGE_RENDERED, () => { recalculateAllStats(); });
        }

        eventSource.on(event_types.GENERATE_AFTER_DATA, (generate_data) => {
            if (extension_settings[MODULE_NAME].useMacro && generate_data) {
                const promptText = getCombinedSocial();
                let replacements = 0;

                if (Array.isArray(generate_data.messages)) {
                    replacements += replaceMacroDeep(generate_data.messages, promptText);
                }

                replacements += replaceMacroDeep(generate_data, promptText);

                if (replacements > 0) {
                    setSocialParseDebug('injecting', `Макрос {{bb_vn}} внедрён: ${replacements}`);
                } else {
                    setSocialParseDebug('checking', 'Режим макроса активен. Прямой {{bb_vn}} в generate_data не найден, возможно он уже был развёрнут пресетом ранее.');
                }
            }
        });

    } catch (e) { console.error("[BB VN] Ошибка запуска:", e); }
});
