/* global jQuery, SillyTavern */
import { extension_settings } from '../../../extensions.js';
import { MODULE_NAME, DEFAULT_SETTINGS, normalizeImpactSettings, normalizeVnReplyLength } from './modules/constants.js';
import { 
    injectCombinedSocialPrompt, 
    recalculateAllStats, 
    setRenderHudCallback,
    getCombinedSocial,
    getCurrentPersonaScopeKey
} from './modules/social.js';
import { 
    ensureHudContainer, 
    updateHudVisibility, 
    renderSocialHud,
    openSocialHud,
    closeSocialHud
} from './modules/hud.js';
import { setupExtensionSettings, wipeGlobalLog, wipeAllSocialData, injectDebugData } from './modules/settings.js';
import { injectVNActionsUI } from './modules/actions.js';
import { restoreVNOptions, bbVnGenerateOptionsFlow, clearVNOptions } from './modules/generator.js';
import { setSocialParseDebug } from './modules/state.js';

// Глобальный экспорт для консоли и внешних вызовов
window['recalculateAllStats'] = recalculateAllStats;
window['getCombinedSocial'] = getCombinedSocial;
window['injectCombinedSocialPrompt'] = injectCombinedSocialPrompt;
window['bbVnGenerateOptionsFlow'] = bbVnGenerateOptionsFlow;
window['restoreVNOptions'] = restoreVNOptions;
window['clearVNOptions'] = clearVNOptions;
window['injectVNActionsUI'] = injectVNActionsUI;
window['setupExtensionSettings'] = setupExtensionSettings;
window['renderSocialHud'] = renderSocialHud;
window['openSocialHud'] = openSocialHud;
window['closeSocialHud'] = closeSocialHud;
window['wipeGlobalLog'] = wipeGlobalLog;
window['wipeAllSocialData'] = wipeAllSocialData;
window['updateHudVisibility'] = updateHudVisibility;
window['ensureHudContainer'] = ensureHudContainer;
window['injectDebugData'] = injectDebugData;

const PERSONA_SCOPE_POLL_MS = 350;
const AUTO_GEN_INITIAL_DELAY_MS = 350;
const AUTO_GEN_RETRY_DELAY_MS = 450;
const AUTO_GEN_MAX_RETRIES = 24;
let personaScopeMonitorId = null;
let lastObservedPersonaScopeKey = '';
let autoGenTimerId = null;
let lastAutoGeneratedMessageKey = '';
let queuedAutoGeneratedMessageKey = '';
let queuedAutoGeneratedMessageId = -1;
let autoGenRetryCount = 0;

// Инициализация настроек по умолчанию
extension_settings[MODULE_NAME] = {
    ...DEFAULT_SETTINGS,
    ...(extension_settings[MODULE_NAME] || {}),
};
extension_settings[MODULE_NAME].vnReplyLength = normalizeVnReplyLength(extension_settings[MODULE_NAME].vnReplyLength);
extension_settings[MODULE_NAME].impactValues = normalizeImpactSettings(extension_settings[MODULE_NAME].impactValues);

// Привязываем коллбэк отрисовки HUD к логике пересчета статов
setRenderHudCallback(renderSocialHud);

function replaceMacroDeep(target, promptText) {
    const macro = '{{bb_vn}}';
    const countOccurrences = (value) => {
        if (typeof value !== 'string' || !value.includes(macro)) return 0;
        return value.split(macro).length - 1;
    };

    const walk = (value) => {
        if (typeof value === 'string') {
            const replacements = countOccurrences(value);
            return {
                value: replacements > 0 ? value.replace(/\{\{bb_vn\}\}/g, promptText) : value,
                replacements,
            };
        }

        if (Array.isArray(value)) {
            let total = 0;
            for (let i = 0; i < value.length; i++) {
                const result = walk(value[i]);
                value[i] = result.value;
                total += result.replacements;
            }
            return { value, replacements: total };
        }

        if (value && typeof value === 'object') {
            let total = 0;
            for (const key of Object.keys(value)) {
                const result = walk(value[key]);
                value[key] = result.value;
                total += result.replacements;
            }
            return { value, replacements: total };
        }

        return { value, replacements: 0 };
    };

    return walk(target).replacements;
}

jQuery(async () => {
    try {
        const { eventSource, event_types } = SillyTavern.getContext();
        const clearScheduledAutoGen = ({ clearQueue = true } = {}) => {
            if (autoGenTimerId) {
                window.clearTimeout(autoGenTimerId);
                autoGenTimerId = null;
            }
            if (clearQueue) {
                queuedAutoGeneratedMessageKey = '';
                queuedAutoGeneratedMessageId = -1;
                autoGenRetryCount = 0;
            }
        };

        const resetAutoGenQueue = () => {
            clearScheduledAutoGen({ clearQueue: false });
            queuedAutoGeneratedMessageKey = '';
            queuedAutoGeneratedMessageId = -1;
            autoGenRetryCount = 0;
        };

        const isStopButtonVisible = () => jQuery('#mes_stop').is(':visible');

        const hasRenderedOptionsForLatestMessage = () => {
            const container = document.getElementById('bb-vn-options-container');
            return !!container?.querySelector('.bb-vn-option[data-intent]');
        };

        const getAssistantMessageMeta = (preferredMessageId = null) => {
            const context = SillyTavern.getContext?.();
            const chat = Array.isArray(context?.chat) ? context.chat : [];
            if (chat.length === 0) return null;

            const normalizedMessageId = Number(preferredMessageId);
            const hasPreferredMessageId = Number.isInteger(normalizedMessageId)
                && normalizedMessageId >= 0
                && normalizedMessageId < chat.length;
            const messageIndex = hasPreferredMessageId ? normalizedMessageId : chat.length - 1;
            const message = chat[messageIndex];
            if (!message || message.is_user) return null;

            const latestMessageIndex = chat.length - 1;
            if (messageIndex !== latestMessageIndex) return null;

            const messageText = String(message.mes || message.message || '').trim();
            const swipeId = String(message.swipe_id ?? 0);
            const sendDate = String(message.send_date || '');
            const genFinished = String(message.gen_finished || '');
            const messageName = String(message.name || message.original_name || '').trim();

            return {
                key: [messageIndex, swipeId, sendDate, genFinished, messageName].join('|'),
                messageId: messageIndex,
                text: messageText,
            };
        };

        const getAutoGenProbeStatus = () => {
            if (!extension_settings[MODULE_NAME].autoGen) return { state: 'abort', reason: 'disabled' };
            if (!queuedAutoGeneratedMessageKey || queuedAutoGeneratedMessageId < 0) return { state: 'abort', reason: 'no-target' };

            const assistantMessage = getAssistantMessageMeta(queuedAutoGeneratedMessageId);
            if (!assistantMessage?.key) return { state: 'abort', reason: 'message-missing' };
            if (assistantMessage.key !== queuedAutoGeneratedMessageKey) return { state: 'abort', reason: 'message-changed' };
            if (!assistantMessage.text) return { state: 'retry', reason: 'empty-message' };
            if (assistantMessage.key === lastAutoGeneratedMessageKey) return { state: 'abort', reason: 'already-generated' };

            const textarea = document.querySelector('#send_textarea');
            if (textarea instanceof HTMLTextAreaElement && textarea.value.trim().length > 0) {
                return { state: 'abort', reason: 'textarea-not-empty' };
            }

            if (hasRenderedOptionsForLatestMessage()) {
                return { state: 'abort', reason: 'options-already-rendered' };
            }

            if (isStopButtonVisible()) {
                return { state: 'retry', reason: 'main-generation-active' };
            }

            const generateButton = jQuery('#bb-vn-btn-generate');
            if (!generateButton.length) {
                return { state: 'retry', reason: 'button-missing' };
            }

            if (generateButton.hasClass('loading')) {
                return { state: 'abort', reason: 'vn-generation-active' };
            }

            return {
                state: 'ready',
                key: assistantMessage.key,
            };
        };

        const scheduleAutoGenProbe = (delayMs = AUTO_GEN_RETRY_DELAY_MS) => {
            clearScheduledAutoGen({ clearQueue: false });
            if (!queuedAutoGeneratedMessageKey || queuedAutoGeneratedMessageId < 0) return;
            autoGenTimerId = window.setTimeout(() => {
                autoGenTimerId = null;
                runAutoGenProbe();
            }, delayMs);
        };

        const runAutoGenProbe = () => {
            const probeStatus = getAutoGenProbeStatus();
            if (probeStatus.state === 'ready' && probeStatus.key) {
                const targetKey = probeStatus.key;
                lastAutoGeneratedMessageKey = targetKey;
                resetAutoGenQueue();
                console.debug('[BB VN][auto] triggering VN auto-generation for', targetKey);
                void bbVnGenerateOptionsFlow();
                return;
            }

            if (probeStatus.state === 'abort') {
                console.debug('[BB VN][auto] cancelled:', probeStatus.reason);
                resetAutoGenQueue();
                return;
            }

            autoGenRetryCount += 1;
            if (autoGenRetryCount > AUTO_GEN_MAX_RETRIES) {
                console.debug('[BB VN][auto] timed out while waiting for UI to settle');
                resetAutoGenQueue();
                return;
            }

            scheduleAutoGenProbe(AUTO_GEN_RETRY_DELAY_MS);
        };

        const queueAutoGenForMessage = (messageId = null) => {
            if (!extension_settings[MODULE_NAME].autoGen) {
                resetAutoGenQueue();
                return;
            }

            const assistantMessage = getAssistantMessageMeta(messageId);
            if (!assistantMessage?.key || !assistantMessage.text) return;
            if (assistantMessage.key === lastAutoGeneratedMessageKey) return;

            queuedAutoGeneratedMessageKey = assistantMessage.key;
            queuedAutoGeneratedMessageId = assistantMessage.messageId;
            autoGenRetryCount = 0;
            console.debug('[BB VN][auto] queued latest assistant message for auto-generation', assistantMessage.key);
            scheduleAutoGenProbe(AUTO_GEN_INITIAL_DELAY_MS);
        };

        const syncPersonaScopeIfChanged = (force = false) => {
            if (typeof document !== 'undefined' && document.hidden) return;
            const currentScopeKey = getCurrentPersonaScopeKey();
            if (!force && currentScopeKey === lastObservedPersonaScopeKey) return;
            lastObservedPersonaScopeKey = currentScopeKey;
            restoreVNOptions(false);
            injectCombinedSocialPrompt();
            recalculateAllStats();
            updateHudVisibility();
        };

        const registerHudVisibilityRecoveryEvents = () => {
            const recoveryEventCandidates = [
                'CHAT_CREATED',
                'CHAT_LOADED',
                'CHARACTER_CHANGED',
                'GROUP_UPDATED',
                'GROUP_CHAT_CREATED',
                'GROUP_CHAT_DELETED',
                'IMPERSONATE_READY',
                'SETTINGS_LOADED_AFTER',
            ];

            recoveryEventCandidates.forEach((eventKey) => {
                const eventName = event_types[eventKey];
                if (!eventName) return;
                eventSource.on(eventName, () => {
                    injectCombinedSocialPrompt();
                    recalculateAllStats();
                    updateHudVisibility();
                });
            });
        };
        
        setupExtensionSettings();

        const context = SillyTavern.getContext();
        if (context.registerMacro) {
            context.registerMacro('bb_vn', () => {
                return extension_settings[MODULE_NAME].useMacro ? getCombinedSocial() : '';
            });
        }

        injectCombinedSocialPrompt();
        ensureHudContainer();
        injectVNActionsUI();
        updateHudVisibility();
        lastObservedPersonaScopeKey = getCurrentPersonaScopeKey();

        if (!personaScopeMonitorId) {
            personaScopeMonitorId = window.setInterval(() => {
                syncPersonaScopeIfChanged(false);
            }, PERSONA_SCOPE_POLL_MS);
        }

        eventSource.on(event_types.APP_READY, () => {
            resetAutoGenQueue();
            lastAutoGeneratedMessageKey = '';
            setupExtensionSettings();
            injectCombinedSocialPrompt();
            ensureHudContainer();
            injectVNActionsUI();
            recalculateAllStats(); 
            updateHudVisibility();
            syncPersonaScopeIfChanged(true);
        });
        
        eventSource.on(event_types.CHAT_CHANGED, () => {
            resetAutoGenQueue();
            lastAutoGeneratedMessageKey = '';
            restoreVNOptions(false);
            injectCombinedSocialPrompt();
            injectVNActionsUI();
            recalculateAllStats(); 
            updateHudVisibility();
            syncPersonaScopeIfChanged(true);
        });

        registerHudVisibilityRecoveryEvents();

        eventSource.on(event_types.MESSAGE_RECEIVED, (messageId) => {
            restoreVNOptions(false);
            recalculateAllStats(true);
            queueAutoGenForMessage(messageId);
        });
        eventSource.on(event_types.MESSAGE_DELETED, () => {
            resetAutoGenQueue();
            restoreVNOptions(false);
            recalculateAllStats();
        });
        eventSource.on(event_types.MESSAGE_SWIPED, () => {
            resetAutoGenQueue();
            restoreVNOptions(false);
            recalculateAllStats();
        });
        eventSource.on(event_types.MESSAGE_UPDATED, () => { recalculateAllStats(); });
        eventSource.on(event_types.GENERATION_STOPPED, () => {
            resetAutoGenQueue();
            recalculateAllStats(true);
        });
        if (event_types.GENERATION_ENDED) {
            eventSource.on(event_types.GENERATION_ENDED, () => {
                recalculateAllStats(true);
                if (queuedAutoGeneratedMessageKey && queuedAutoGeneratedMessageId >= 0) {
                    scheduleAutoGenProbe(AUTO_GEN_INITIAL_DELAY_MS);
                }
            });
        }
        
        if (event_types.CHARACTER_MESSAGE_RENDERED) {
            eventSource.on(event_types.CHARACTER_MESSAGE_RENDERED, (messageId) => {
                recalculateAllStats();
                queueAutoGenForMessage(messageId);
            });
        }

        eventSource.on(event_types.GENERATE_AFTER_DATA, (generate_data) => {
            if (extension_settings[MODULE_NAME].useMacro && generate_data) {
                const promptText = getCombinedSocial();
                let replacements = 0;

                if (Array.isArray(generate_data.messages)) {
                    replacements += replaceMacroDeep(generate_data.messages, promptText);
                }

                replacements += replaceMacroDeep(generate_data, promptText);

                if (replacements > 0) {
                    setSocialParseDebug('injecting', `Макрос {{bb_vn}} внедрён: ${replacements}`);
                } else {
                    setSocialParseDebug('checking', 'Режим макроса активен. Прямой {{bb_vn}} в generate_data не найден, возможно он уже был развёрнут пресетом ранее.');
                }
            }
        });

    } catch (e) { console.error("[BB VN] Ошибка запуска:", e); }
});
